//ACCOUNT
export const CHANGE_NAME = 'CHANGE_NAME';

// EVENTS
export const CREATE_EVENT = 'CREATE_EVENT';
export const SEND_EVENT = 'SEND_EVENT';

// FRIENDS
export const ADD_FRIEND = 'ADD_FRIEND';

// FRIEND GROUPS
export const ADD_FRIEND_GROUP = 'ADD_FRIEND_GROUP';

// OTHER
export const SET_EVENTS_COUNTER = 'SET_EVENTS_COUNTER';
